### PR TITLE
Re-enable aarch64

### PR DESCRIPTION
**Pull request by hfiguiere**
This is on top of #21  to reenable aarch64

I haven't tested it yet.

cc @aleb

### CODE REVIEW

**Comment by hfiguiere** [comment]
bot, build

**Comment by aleb** [comment]
bot, build

**Comment by aleb** [comment]
bot, build

**Comment by hfiguiere** [comment]
urgh, forgot to reenable aarch64...

**Comment by hfiguiere** [comment]
Tested it on Raspberry Pi

**Comment by aleb** [comment]
Thank you! Do you want to squash your commits into my first commit to keep history clean, or do you prefer to leave them like this?

We could use the same manifest backed by source archives for both x86_64 and aarch64. It would be simpler for me to merge the changes as they are, and then I'll change upstream to build matplotlib from source, so we have a single manifest for both architectures.

**Comment by hfiguiere** [comment]
I was thinking reorganizing these a bit.

**Comment by thiblahute** [comment]
Thanks!

**Pull request merged**
