### PR TITLE
22.06 update

### PR DESCRIPTION
**Pull request by hfiguiere**
This supercede #32 (or not)

### CODE REVIEW

**Comment by hfiguiere** [comment]
@aleb this did build locally. It's based on your PR. I haven't tested it yet.

**Comment by hfiguiere** [comment]
I get:
```
** (gst-plugin-scanner:5): CRITICAL **: 17:26:56.249: Couldn't g_module_open libpython. Reason: /usr/lib/x86_64-linux-gnu/libpython3.9.so: cannot open shared object file: No such file or directory
```

But i'm not sure how bad that is. Also I think I have seen it in the past.

**Comment by hfiguiere** [comment]
It runs and open projects.

**Comment by aleb** [comment]
I get this when opening a project and selecting a file:
```
Traceback (most recent call last):
  File "/app/lib/pitivi/python/pitivi/clip_properties/compositing.py", line 247, in _source_deep_notify_cb
    self._update_blending()
  File "/app/lib/pitivi/python/pitivi/clip_properties/compositing.py", line 238, in _update_blending
    res, value = self._video_source.get_child_property("operator")
TypeError: unknown type (null)
```

I'll update GStreamer

**Comment by aleb** [comment]
What is the reason for using lapack lapack-3.8.0.tar.gz instead of v3.10.1.tar.gz?

**Comment by aleb** [comment]
I'm not sure when I'll be able to update GStreamer. It's supposed to be trivial, but I'm not sure how it's supposed to be done now with the mono repo. Maybe at the end of next week I can do it, or in three weeks for sure. 

If anybody gets to update GSTreamer I can give the build a spin to try it out.

**Comment by hfiguiere** [comment]
This time with gstreamer 1.20.3

**Comment by hfiguiere** [comment]
Seems to work for me, but I never got the error you mentionned above.

**Comment by hfiguiere** [comment]
@aleb can we get one of the PR merged?

**Comment by aleb** [comment]
If it works for you, sure. It should be fine. I can only test on Monday.

**Pull request merged**
