### PR TITLE
Update to GNOME 45

### PR DESCRIPTION
**Pull request by hfiguiere**
- Update to GNOME 45
- Revert a checksum change
- Use the new syntax for MIME

### CODE REVIEW

**Comment by hfiguiere** [comment]
Fail to start:
```
ERROR — Could not create a Gst.Fraction — this means gst-python is not installed correctly.
```

**Comment by thiblahute** [comment]
I guess that is due to https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3353: https://gitlab.gnome.org/GNOME/pygobject/-/issues/624

**Comment by hfiguiere** [comment]
I'll update to 45 then, it seems to work there. that leave a bit more time for stuff to be fixed.

**Comment by hfiguiere** [comment]
seems to work here.

**Pull request merged**
