### PR TITLE
Use shared-modules/libcanberra

### PR DESCRIPTION
**Pull request by A6GibKm**
Includes an important patch for wayland.

### CODE REVIEW

**Comment by hfiguiere** [comment]
See #24 for how to fix the issue with gsound.

**Comment by A6GibKm** [comment]
gsound is not working since gitlab was down, now it should work. But I agree that it should use the archive at download.gnome.org.

**Comment by A6GibKm** [comment]
bot, build

**Comment by hfiguiere** [comment]
Same PR for soundtouch. It moved.

**Pull request closed without merging**
