### PR TITLE
Update to 2023.03.0

### LINKED ISSUE #35: Update to 23.03
There is a tag for 23.03.

(albeit I see no update on the website)

### PR DESCRIPTION
**Pull request by AsciiWolf**
Closes #35.

### CODE REVIEW

**Comment by aleb** [comment]
Might want to check the history of updates we did to the manifest we use for development since the last release:
https://gitlab.gnome.org/GNOME/pitivi/-/commits/master/build/flatpak

**Comment by AsciiWolf** [comment]
It looks like that these are the only two differences:

https://gitlab.gnome.org/GNOME/pitivi/-/commit/581f451adb206d66243bbce7ce0c88cfa61aafee
https://gitlab.gnome.org/GNOME/pitivi/-/commit/a067ed95003a13f196a198c7468e6bf777e58fe4

**Comment by AsciiWolf** [comment]
I have added the soundtouch patch. I am however not sure about the gstreamer changes since they seem quite big and could cause issues. I would prefer to not include them in this PR.

/cc @hfiguiere

**Comment by aleb** [comment]
The switch to the GStreamer mono repo should be easy.

@thiblahute what GStreamer version should we use?

**Comment by AsciiWolf** [comment]
By the way, the ffmpeg version used by this Flatpak seems to be quite outdated. I can update it if you want. OpenCV is another example of a module that could be updated.

**Comment by aleb** [comment]
Re ffmpeg, I think it depends on what GStreamer version we want. @thiblahute

**Comment by thiblahute** [comment]
We should use at GStreamer 1.22

**Comment by AsciiWolf** [comment]
Other dependencies that could be updated are:

_lapack_ to version **3.11.0**
_x264_ to version **20191217-2245**
_frei0r-plugin_ to version **2.3.1** (if there was no compatibility breaking abi change from 1.x)
_fdkaac_ to version **2.0.2** (if there was no compatibility breaking abi change from 1.x)
_libpeas_ to version **1.36.0**

**Comment by aleb** [comment]
It should be fine to update these. We can also update them some other time.

**Comment by AsciiWolf** [comment]
It looks like that the aarch64 build did hang on "patching file 3rdparty/carotene/CMakeLists.txt" for some reason.

**Comment by AsciiWolf** [comment]
bot, build

**Comment by AsciiWolf** [comment]
Ah, the problematic patch is for aarch64 only. :-) I have removed it since it is most likely not relevant anymore.

**Comment by AsciiWolf** [comment]
> Build [62498 successful](https://buildbot.flathub.org/#/builders/6/builds/62498) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/45130/org.pitivi.Pitivi.flatpakref
> ```

Tested and seems to work fine, although it needs more testing to assure that all parts (including OpenCV etc.) work correctly.

**Comment by aleb** [comment]
seems to work fine, thanks!

**Comment by AsciiWolf** [comment]
@hfiguiere Is there anything preventing this PR from being merged? Thanks!

**Pull request merged**
