### PR TITLE
Update to Pitivi 2022.06 and latest Matplotlib

### PR DESCRIPTION
**Pull request by aleb**

### CODE REVIEW

**Comment by hfiguiere** [comment]
scikit-learn seems to be part of the problem.

**Comment by aleb** [comment]
bot, build

**Comment by aleb** [comment]
```
  numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found.
  To build Scipy from sources, BLAS & LAPACK libraries need to be installed.
  See site.cfg.example in the Scipy source directory and
  https://docs.scipy.org/doc/scipy/reference/building/index.html for details.
```

**Comment by hfiguiere** [comment]
I have some improvements here https://github.com/flathub/org.pitivi.Pitivi/tree/22.06-update (from yesterday state of your PR), notably BLAS and some of the build-options for it to be found but it still doesn't build (further errors)

Fill free to pick what you find useful.

**Comment by hfiguiere** [comment]
I rebased my branch onto yours, and scikit build fine now. but llmvlite choke on the lack of llvm11 wich doesn't exist for 21.08. I need to create one.

**Comment by hfiguiere** [comment]
Related PR https://github.com/flathub/org.freedesktop.Sdk.Extension.llvm11/pull/14

**Comment by hfiguiere** [comment]
What I suggest doing right now, is updating to 22.06 and forgo librosa until there is the proper llvm11 sdk. Working on it though, but it might take longer than that.

**Comment by aleb** [comment]
I kind of get the idea, but it does not compare to actually seeing the error. 

random thought: Another thing we can do is update matplotlib to at least 3.4.0, see https://github.com/flathub/org.pitivi.Pitivi/issues/31

If people care we could do an incremental build, I thought about that but I prefer to have it all at once.

**Comment by aleb** [comment]
Something like this I guess:
```
Successfully built audioread numba resampy scikit-learn cffi
Failed to build llvmlite
Installing collected packages: audioread, appdirs, urllib3, threadpoolctl, pycparser, packaging, llvmlite, joblib, idna, decorator, charset-normalizer, scikit-learn, requests, numba, cffi, soundfile, resampy, pooch, librosa
  Running command Running setup.py install for llvmlite
  running install
  /usr/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  running build
  got version from file /tmp/pip-install-6s1g_6kg/llvmlite_66c3664ff7514d94b816fa8fd874b4c3/llvmlite/_version.py {'version': '0.38.1', 'full': '650c36d5a79e3825d26fb44f4abd853729a9b959'}
  running build_ext
  /usr/bin/python3 /tmp/pip-install-6s1g_6kg/llvmlite_66c3664ff7514d94b816fa8fd874b4c3/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-6s1g_6kg/llvmlite_66c3664ff7514d94b816fa8fd874b4c3/ffi/build.py", line 220, in <module>
      main()
    File "/tmp/pip-install-6s1g_6kg/llvmlite_66c3664ff7514d94b816fa8fd874b4c3/ffi/build.py", line 210, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-6s1g_6kg/llvmlite_66c3664ff7514d94b816fa8fd874b4c3/ffi/build.py", line 134, in main_posix
      raise RuntimeError(msg) from None
  RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
  error: command '/usr/bin/python3' failed with exit code 1
  error: subprocess-exited-with-error
  
  × Running setup.py install for llvmlite did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python3 -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize
  
  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)
  
  __file__ = %r
  sys.argv[0] = __file__
  
  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/tmp/pip-install-6s1g_6kg/llvmlite_66c3664ff7514d94b816fa8fd874b4c3/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' install --record /tmp/pip-record-8yjprihy/install-record.txt --single-version-externally-managed --prefix /app --compile --install-headers /app/include/python3.9/llvmlite
  cwd: /tmp/pip-install-6s1g_6kg/llvmlite_66c3664ff7514d94b816fa8fd874b4c3/
  Running setup.py install for llvmlite ... error
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> llvmlite

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
Error: module python3-librosa: Child process exited with code 1
```

**Comment by aleb** [comment]
It timed out :/

**Comment by hfiguiere** [comment]
it's an actual build error on opencv

**Comment by hfiguiere** [comment]
I get a different error with lapack 3.8. (link errors - and I haven't investigated)

Adding `"-DWITH_LAPACK=OFF",` to opencv `config-opts` however will disable LAPACK which wasn't present before, and this allow the build to pass.

**Comment by hfiguiere** [comment]
btw, I would put the lapack module in the main manifest.

**Comment by hfiguiere** [comment]
This was integrated into #33

**Pull request merged**
